In [1]:
import numpy as np
import pandas as pd

In [ ]:
np.arange, np.array, np.zeros, np.ones, np.empty
np.random.randint, np.random.rand

In [8]:
np.arange(10).reshape(2, 5).size #

10

In [9]:
np.zeros((2,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.random.rand(2, 5)

array([[ 0.79003919,  0.50444038,  0.3893047 ,  0.05419613,  0.06322909],
       [ 0.51819175,  0.12653404,  0.95584603,  0.63835925,  0.26588111]])

In [17]:
np.eye(5) * 10

array([[ 10.,   0.,   0.,   0.,   0.],
       [  0.,  10.,   0.,   0.,   0.],
       [  0.,   0.,  10.,   0.,   0.],
       [  0.,   0.,   0.,  10.,   0.],
       [  0.,   0.,   0.,   0.,  10.]])

In [14]:
np.exp(np.eye(5))

array([[ 2.71828183,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  2.71828183,  1.        ,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  2.71828183,  1.        ,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  2.71828183,  1.        ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  2.71828183]])

In [19]:
np.linalg.inv(np.eye(5)*10)

array([[ 0.1,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0.1,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0.1,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0.1,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.1]])

### индексация

In [38]:
B = np.arange(12).reshape(2, 2, 3)
B

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [24]:
A = np.arange(15).reshape(5, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [46]:
choise = np.arange(A.shape[1]) % 2 == 0
A[:, choise]

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11],
       [12, 14]])

### broadcasting

In [51]:
A.shape

(5, 3)

In [60]:
b = np.arange(5)
b.shape

(5,)

In [55]:
b[np.newaxis, :]

array([[ 1.,  1.,  1.]])

In [62]:
A * b[:, np.newaxis]

array([[ 0,  0,  0],
       [ 3,  4,  5],
       [12, 14, 16],
       [27, 30, 33],
       [48, 52, 56]])

In [68]:
b, b[:, np.newaxis]

(array([0, 1, 2, 3, 4]), array([[0],
        [1],
        [2],
        [3],
        [4]]))

In [66]:
A.T.dot(b)

array([ 90, 100, 110])

In [67]:
A.T@b

array([ 90, 100, 110])

In [79]:
a = np.random.randint(5, size=3)
b = np.random.randint(4, size=2)

In [82]:
a[:, np.newaxis] @ b[np.newaxis, :]

array([[8, 4],
       [4, 2],
       [2, 1]])

In [80]:
a, b

(array([4, 2, 1]), array([2, 1]))

In [84]:
np.min(A, axis=0)

array([0, 1, 2])

In [85]:
np.cumsum(a)

array([4, 6, 7])

In [86]:
np.cumsum(A, axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15],
       [18, 22, 26],
       [30, 35, 40]])

In [116]:
np.concatenate((A, A[-2:-1, :]), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [ 9, 10, 11]])

In [102]:
A[:, -1:]

array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14]])

In [ ]:
np.insert(A, np.arange(5))

In [87]:
# X (l x d), y; w - ?
def linregr(X, y, lambda_1 = 1):
    coefs = np.linalg.inv(X.T @ X + lambda_1 * np.eye(X.shape[1])) @ X.T @ y
    return coefs

In [89]:
l = 100
d = 7
X = np.random.rand(l, d)
y = np.random.rand(l)
linregr(X, y, lambda_1 = 10 ** 7)

array([  2.46900851e-06,   2.41114227e-06,   2.55604515e-06,
         2.49172572e-06,   2.51440284e-06,   2.58660800e-06,
         2.36133215e-06])

In [125]:
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 2, np.arange(3), axis=1)

array([[1],
       [2],
       [3]])

In [131]:
### Задача 2:  X, поделить каждую строку на сумму элементов в ней
a = np.sum(X, axis=1)
X/a.reshape(-1,1)


array([[  2.50096284e-01,   3.48550914e-02,   1.68107776e-01,
          6.93582537e-02,   1.05328874e-03,   1.55375525e-01,
          3.21153781e-01],
       [  1.41430766e-01,   1.46238536e-01,   1.01388633e-02,
          1.76995727e-01,   1.57991069e-01,   1.85094395e-01,
          1.82110643e-01],
       [  7.47530665e-02,   5.30451439e-02,   3.65979488e-01,
          2.83782381e-02,   2.65734490e-01,   6.27692195e-03,
          2.05832652e-01],
       [  1.43430303e-01,   2.20823941e-02,   3.78917374e-02,
          2.02525807e-01,   3.20593911e-01,   9.39537270e-03,
          2.64080474e-01],
       [  1.62289550e-01,   1.19426328e-01,   5.82589797e-02,
          2.63183591e-01,   2.34771006e-01,   4.46369735e-02,
          1.17433571e-01],
       [  1.26086513e-02,   2.54747917e-01,   6.29939557e-02,
          2.46349983e-01,   2.14537387e-01,   7.81559533e-02,
          1.30606153e-01],
       [  1.92334585e-01,   1.65716227e-01,   1.12301414e-01,
          1.40889240e-01,   3.62

In [143]:
a = np.random.rand(l)
y = np.random.randint(2, size=l)

In [140]:
idxs = np.argsort(a)

In [144]:
y[idxs]

array([1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0])

In [145]:
czz

array([ 0,  1,  3,  6, 10])

In [152]:
def revers_cumsum(x):
    return np.cumsum(x[::-1])[::-1]

In [153]:
revers_cumsum(np.arange(3))

array([3, 3, 2])

In [156]:
def roc_auc(y, a):
    lp = y.sum()
    lm = len(y) - lp
    indexes = np.argsort(a)
    y_sorted = y[ indexes ]
    ones_right = revers_cumsum(y_sorted)
    return ones_right[ y_sorted == 0 ].sum()/ lp / lm

In [157]:
roc_auc(y, a)

0.48067632850241543

In [158]:
from sklearn.metrics import roc_auc_score

In [159]:
roc_auc_score(y, a)

0.48067632850241543

In [162]:
df = pd.DataFrame({"a":[1, 2, 3], "b":[1, 1, 1]})
df


a  b
0  1  1
1  2  1
2  3  1

In [163]:
df.columns, df.index

(Index(['a', 'b'], dtype='object'), RangeIndex(start=0, stop=3, step=1))

In [169]:
df = pd.read_csv("https://raw.githubusercontent.com/iad34/seminars/master/materials/data_sem1.csv",
           sep=";")

In [171]:
df.head(7)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   

                                                Name      Sex   Age  SibSp  \
0                            Braund; Mr. Owen Harris     male  22.0      1   
1  Cumings; Mrs. John Bradley (Florence Briggs Th...   female  38.0      1   
2                             Heikkinen; Miss. Laina   female  26.0      0   
3       Futrelle; Mrs. Jacques Heath (Lily May Peel)   female  35.0      1   
4                           Allen; Mr. William Henry     male  35.0      0   
5                                   Moran; Mr. James  unknown   NaN      0   
6                            McCarthy; Mr. Timothy J     male  54.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S

In [172]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [184]:
(df["Name"]+" "+df["Age"].astype(str)).head()

0                         Braund; Mr. Owen Harris 22.0
1    Cumings; Mrs. John Bradley (Florence Briggs Th...
2                          Heikkinen; Miss. Laina 26.0
3    Futrelle; Mrs. Jacques Heath (Lily May Peel) 35.0
4                        Allen; Mr. William Henry 35.0
dtype: object

In [179]:
pd.merge(sales, adresses, on="shop_id")

PassengerId  Survived  Pclass  \
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                           Name     Sex   Age  SibSp  Parch  \
2                        Heikkinen; Miss. Laina  female  26.0      0      0   
3  Futrelle; Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                      Allen; Mr. William Henry    male  35.0      0      0   

             Ticket    Fare Cabin Embarked  
2  STON/O2. 3101282   7.925   NaN        S  
3            113803  53.100  C123        S  
4            373450   8.050   NaN        S

In [199]:
df["Name"].map(lambda x: x.split(";")[0])

0               Braund
1              Cumings
2            Heikkinen
3             Futrelle
4                Allen
5                Moran
6             McCarthy
7              Palsson
8              Johnson
9               Nasser
10           Sandstrom
11             Bonnell
12         Saundercock
13           Andersson
14             Vestrom
15             Hewlett
16                Rice
17            Williams
18       Vander Planke
19          Masselmani
20              Fynney
21             Beesley
22             McGowan
23              Sloper
24             Palsson
25             Asplund
26                Emir
27             Fortune
28             O'Dwyer
29            Todoroff
            ...       
861              Giles
862              Swift
863               Sage
864               Gill
865            Bystrom
866       Duran y More
867           Roebling
868      van Melkebeke
869            Johnson
870             Balkic
871           Beckwith
872           Carlsson
873    Vand

In [193]:
"my name is Nadia".split(" ")[0]

'my'

In [205]:
unigues = set(df["Sex"])
di = {x:i for i, x in enumerate(unigues)}
di

{'female': 0, 'male': 2, 'unknown': 1}

In [208]:
df["Sex"].head(), df["Sex"].map(di).head()

(0      male
 1    female
 2    female
 3    female
 4      male
 Name: Sex, dtype: object, 0    2
 1    0
 2    0
 3    0
 4    2
 Name: Sex, dtype: int64)

In [210]:
se = df["Sex"]
se.map()

0         male
1       female
2       female
3       female
4         male
5      unknown
6         male
7         male
8       female
9       female
10      female
11      female
12        male
13     unknown
14      female
15      female
16        male
17        male
18      female
19      female
20        male
21        male
22      female
23        male
24      female
25      female
26        male
27        male
28     unknown
29        male
        ...   
861       male
862     female
863     female
864       male
865     female
866     female
867       male
868       male
869       male
870       male
871     female
872       male
873       male
874     female
875     female
876       male
877       male
878       male
879     female
880     female
881       male
882     female
883       male
884       male
885     female
886       male
887     female
888     female
889       male
890       male
Name: Sex, Length: 891, dtype: object

In [211]:
def fun(x):
    return x.split(";")[0]

df["Name"].apply(fun)

0               Braund
1              Cumings
2            Heikkinen
3             Futrelle
4                Allen
5                Moran
6             McCarthy
7              Palsson
8              Johnson
9               Nasser
10           Sandstrom
11             Bonnell
12         Saundercock
13           Andersson
14             Vestrom
15             Hewlett
16                Rice
17            Williams
18       Vander Planke
19          Masselmani
20              Fynney
21             Beesley
22             McGowan
23              Sloper
24             Palsson
25             Asplund
26                Emir
27             Fortune
28             O'Dwyer
29            Todoroff
            ...       
861              Giles
862              Swift
863               Sage
864               Gill
865            Bystrom
866       Duran y More
867           Roebling
868      van Melkebeke
869            Johnson
870             Balkic
871           Beckwith
872           Carlsson
873    Vand

In [219]:
df.groupby("Last name").apply(lambda x: x.shape[1])

Last name
Abbing              1
Abbott              2
Abelson             2
Adahl               1
Adams               1
Ahlin               1
Aks                 1
Albimona            1
Alexander           1
Alhomaki            1
Ali                 2
Allen               2
Allison             3
Allum               1
Andersen-Jensen     1
Anderson            1
Andersson           9
Andreasson          1
Andrew              1
Andrews             2
Angle               1
Appleton            1
Arnold-Franchi      2
Artagaveytia        1
Asim                1
Asplund             4
Astor               1
Attalah             2
Aubart              1
Augustsson          1
                   ..
Wells               1
West                3
Wheadon             1
White               2
Wick                2
Widegren            1
Widener             1
Wiklund             1
Wilhelms            1
Willey              1
Williams            4
Williams-Lambert    1
Windelov            1
Wiseman             1


In [220]:
df.shape

(891, 13)